### ISSUE TITLE
[Refact] Act, Todo, Plan 도메인 기본 응답형식 적용

### ISSUE THREAD

**Issue by uzz99** [beyond-sw-camp/be08-fin-3Dasoo-SalesBoost#40]
## 📃 작업 설명
>  Act, Todo, Plan 도메인에 기본 응답/에러 형식 적용
> Swagger API 문서 개선
<br>

## ✔️ 작업 상세 내용
- [x] Act 기본 응답/에러 형식 적용
- [x] Act Swagger tag, des, schema
- [x] Plan 기본 응답/에러 형식 적용
- [x] Plan Swagger tag, des, schema
- [x] Todo 기본 응답/에러 형식 적용

<br>

## 🆔 관련 요구사항 ID
REQ201, 202, 205, 602
